package main

import (
	crand "crypto/rand"
	"fmt"
	"log"
	"math/big"
	"math/rand"
	"time"
)

func main() {
	/* in go there are two type in which random number is generated
	1. random number generated by mathematical expression (which can be repeated)
	2. through cryptography algorightm (more surity about the random number being random)
	*/

	// first case throught mathematical
	rand.Seed(int64(time.Now().Nanosecond())) // to make this seed random we can use system time
	fmt.Println("Random number from mathematical algorithm :", rand.Intn(10))

	// random number from cryptography
	n := big.NewInt(5) // upper limit (0 to 4)
	myRandomNumber, err := crand.Int(crand.Reader, n)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Random number from cryptograpy :", myRandomNumber)
}
